### PR TITLE
Porting tesseract/gh_pages

### PR DESCRIPTION
**Pull request by steviedale**
Moving gh_pages contents from https://github.com/ros-industrial-consortium/tesseract.git --> https://github.com/ros-industrial-consortium/tesseract_docs.git

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Will the `gh_pages` branch be purged from `tesseract` itself?

**Comment by Levi-Armstrong** [comment]
I believe so. Is that the only way to solve the cloning issues is purging it from the history?

**Comment by gavanderhoorn** [comment]
It's a disconnected branch, so deleting it should be sufficient to bring down the repository size.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: are you still planning to remove the `gh-pages` branch? [ros-industrial-consortium/tesseract/branches](https://github.com/ros-industrial-consortium/tesseract/branches) still lists it as being *active*.

**Pull request merged**
